import 'dart:io';

import 'package:uuid/uuid.dart';

const uuid = Uuid();

class Place {

  //': id = uuid.v4()'; is an initializer list. 
  // It's used to initialize final fields before the constructor's body is executed.
  // to ensure a unique id is generated by uuid.v4()
  Place({required this.title, required this.image}) : id = uuid.v4();

  final String id;
  final String title;
  final File image;
}